ALTER TABLE pharmacies 
ADD COLUMN IF NOT EXISTS opening_hours_start TIME DEFAULT '08:00',
ADD COLUMN IF NOT EXISTS opening_hours_end TIME DEFAULT '18:00',
ADD COLUMN IF NOT EXISTS auto_open_status BOOLEAN DEFAULT FALSE;
